name: gogo

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: gogo_litellm
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--detailed_debug" ]
    env_file:
      - .env
    restart: always
